import Navbar from "@/components/Navbar"
import Sidebar from "@/components/Sidebar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="flex">
          <div className="hidden md:block h-[100vh]">
            <Sidebar />
          </div>
          <div className="p-5 w-ful md:max-w-[1140px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
